const VENUES = [
  {
    id: 136,
    location: 2,
    name: 'Address Boulevard',
    total_capacity: 0,
    lat: 25.2009,
    lon: 55.2763,
    review_count: 0,
    average_rating: 0.0,
    featured_image:
      'https://staging.letswork.io/media/branch_images/reading_room_-min.jpg',
    food_policy: 'Test',
    checkin_instructions: 'test',
    address: 'Sheikh Mohammed bin Rashid Blvd, Downtown Dubai',
    facilities: [
      {
        name: 'Free Parking',
        icon: 'https://staging.letswork.io/media/facilities/f_free_parking.png',
      },
      {
        name: 'Meeting Rooms',
        icon: 'https://staging.letswork.io/media/facilities/f_meeting_rooms.png',
      },
      {
        name: 'Prayer Room',
        icon: 'https://staging.letswork.io/media/facilities/f_prayer_room.png',
      },
      {
        name: 'Toilets',
        icon: 'https://staging.letswork.io/media/facilities/f_toilets.png',
      },
      {
        name: 'WiFi',
        icon: 'https://staging.letswork.io/media/facilities/f_wifi.png',
      },
    ],
    wifi_password: null,
    wifi_name: null,
    speciality: null,
    media: [
      {
        id: 911,
        title: null,
        media_type: 'Image',
        media_url:
          'https://staging.letswork.io/media/branch_images/reading_room_-min.jpg',
        is_front: true,
      },
    ],
    thumbnail:
      'https://staging.letswork.io/media/med/400x400_resized_reading_room_-min.jpg',
    timings: '09:00 - 23:00',
    is_open: 1,
    is_branch_open: 'Open until 23:00',
    content_type_id: 12,
    no_checkin_members: 0,
    premium: false,
    is_premium: 0,
    is_women_only: 0,
    is_dca_approved_only: 0,
    allowed_plan_ids: [
      101, 114, 112, 111, 113, 91, 109, 106, 88, 102, 90, 92, 89, 105, 100,
    ],
    is_favorite: null,
    is_at_full_capacity: true,
    credits_required: 0,
    is_ddr: false,
    total_capacity_ar: '٠',
    credits_required_ar: '٠',
    spotLeft: 0,
    spotLeft_ar: '٠',
    review_count_ar: '٠',
    branch_cost: 'AED 0',
    branch_cost_ar: 'AED ٠',
  },
  {
    id: 162,
    location: 2,
    name: 'Airwerks Cafe',
    total_capacity: 6,
    lat: 25.186,
    lon: 55.239,
    review_count: 231,
    average_rating: 4.8,
    featured_image:
      'https://staging.letswork.io/media/general/2020-10-08-030012121-min.jpg',
    food_policy:
      'No outside food permitted. Instead, enjoy 20% off your food and beverage order while working from this space.',
    checkin_instructions:
      "When you arrive at the cafe, please check-in on the Letswork App and inform the staff you're with Letswork to get your benefits.",
    address: 'Wasl Square, Al Safa',
    facilities: [
      {
        name: 'Paid Parking',
        icon: 'https://staging.letswork.io/media/facilities/f_paid_parking.png',
      },
      {
        name: 'Toilets',
        icon: 'https://staging.letswork.io/media/facilities/f_toilets.png',
      },
      {
        name: 'WiFi',
        icon: 'https://staging.letswork.io/media/facilities/f_wifi.png',
      },
    ],
    wifi_password: 'airwerkscycles',
    wifi_name: 'Airwerks',
    speciality: 'Cafe - Buzzing - Paid Parking',
    media: [
      {
        id: 530,
        title: null,
        media_type: 'Image',
        media_url:
          'https://staging.letswork.io/media/general/2020-10-08-030012121-min.jpg',
        is_front: false,
      },
      {
        id: 531,
        title: null,
        media_type: 'Image',
        media_url:
          'https://staging.letswork.io/media/general/2020-10-08-030047080-min.jpg',
        is_front: false,
      },
    ],
    thumbnail:
      'https://staging.letswork.io/media/med/400x400_resized_2020-10-08-030012121-min.jpg',
    timings: '08:00 - 22:00',
    is_open: 1,
    is_branch_open: 'Open until 22:00',
    content_type_id: 12,
    no_checkin_members: 4,
    premium: false,
    is_premium: 0,
    is_women_only: 0,
    is_dca_approved_only: 0,
    allowed_plan_ids: [
      101, 114, 112, 111, 113, 91, 109, 106, 88, 102, 90, 92, 89, 105, 100,
    ],
    is_favorite: null,
    is_at_full_capacity: false,
    credits_required: 10,
    is_ddr: false,
    total_capacity_ar: '٦',
    credits_required_ar: '١٠',
    spotLeft: 2,
    spotLeft_ar: '٢',
    review_count_ar: '٢٣١',
    branch_cost: 'AED 50',
    branch_cost_ar: 'AED ٥٠',
  },
  {
    id: 265,
    location: 2,
    name: 'Aj1881',
    total_capacity: 15,
    lat: 25.18186989539031,
    lon: 55.23630578178736,
    review_count: 260,
    average_rating: 5.0,
    featured_image:
      'https://staging.letswork.io/media/general/2021-09-26_aj_18810772_1-min.jpg',
    food_policy:
      'No outside food permitted. Instead, enjoy 20% off your food and beverage order while working from this space.',
    checkin_instructions:
      'Once you arrive at the cafe, please check-in on the Letswork App and inform the staff you are with Letswork to enjoy your benefits.',
    address: 'Al ferdous 2, Shop no. 2, Al Wasl',
    facilities: [
      {
        name: 'Free Parking',
        icon: 'https://staging.letswork.io/media/facilities/f_free_parking.png',
      },
      {
        name: 'Printer',
        icon: 'https://staging.letswork.io/media/facilities/f_printer.png',
      },
      {
        name: 'Toilets',
        icon: 'https://staging.letswork.io/media/facilities/f_toilets.png',
      },
      {
        name: 'WiFi',
        icon: 'https://staging.letswork.io/media/facilities/f_wifi.png',
      },
    ],
    wifi_password: 'aj1881@2022',
    wifi_name: 'Aj1881',
    speciality: 'Cafe - Quiet - Free Parking',
    media: [
      {
        id: 629,
        title: '1IMG',
        media_type: 'Image',
        media_url:
          'https://staging.letswork.io/media/general/2021-09-26_aj_18810772_1-min.jpg',
        is_front: false,
      },
      {
        id: 630,
        title: '2IMG',
        media_type: 'Image',
        media_url:
          'https://staging.letswork.io/media/general/2021-09-26_aj_18810770_1-min.jpg',
        is_front: false,
      },
    ],
    thumbnail:
      'https://staging.letswork.io/media/med/400x400_resized_2021-09-26_aj_18810772_1-min.jpg',
    timings: '08:00 - 22:00',
    is_open: 1,
    is_branch_open: 'Open until 22:00',
    content_type_id: 12,
    no_checkin_members: 4,
    premium: false,
    is_premium: 0,
    is_women_only: 0,
    is_dca_approved_only: 0,
    allowed_plan_ids: [
      101, 114, 112, 111, 113, 91, 109, 106, 88, 102, 90, 92, 89, 105, 100,
    ],
    is_favorite: null,
    is_at_full_capacity: false,
    credits_required: 7,
    is_ddr: false,
    total_capacity_ar: '١٥',
    credits_required_ar: '٧',
    spotLeft: 11,
    spotLeft_ar: '١١',
    review_count_ar: '٢٦٠',
    branch_cost: 'AED 35',
    branch_cost_ar: 'AED ٣٥',
  },
  {
    id: 474,
    location: 2,
    name: 'AMG Cafe / Weslodge',
    total_capacity: 20,
    lat: 25.20594780270794,
    lon: 55.26416277199686,
    review_count: 19,
    average_rating: 5.0,
    featured_image: 'https://staging.letswork.io/media/general/1_M1Whvme.jpg',
    food_policy: 'No outside food allowed. 20% discount on food available.',
    checkin_instructions:
      'Once you arrive at the cafe, please check-in on the Letswork App and inform the staff you are with Letswork to enjoy your benefits.',
    address: 'City Walk Dubai',
    facilities: [
      {
        name: 'Free Parking',
        icon: 'https://staging.letswork.io/media/facilities/f_free_parking.png',
      },
      {
        name: 'Prayer Room',
        icon: 'https://staging.letswork.io/media/facilities/f_prayer_room.png',
      },
      {
        name: 'Toilets',
        icon: 'https://staging.letswork.io/media/facilities/f_toilets.png',
      },
      {
        name: 'WiFi',
        icon: 'https://staging.letswork.io/media/facilities/f_wifi.png',
      },
    ],
    wifi_password: 'byod@2020',
    wifi_name: 'Purple-BYOD',
    speciality: 'Cafe - Quiet - Free Parking',
    media: [
      {
        id: 892,
        title: null,
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/general/1_M1Whvme.jpg',
        is_front: true,
      },
      {
        id: 893,
        title: null,
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/general/2_9pXnsZ9.jpg',
        is_front: false,
      },
      {
        id: 894,
        title: null,
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/general/3_k6CBn2E.jpg',
        is_front: false,
      },
      {
        id: 895,
        title: null,
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/general/4_Y0wIGsU.jpg',
        is_front: false,
      },
    ],
    thumbnail:
      'https://staging.letswork.io/media/med/400x400_resized_1_M1Whvme.jpg',
    timings: '08:00 - 22:00',
    is_open: 1,
    is_branch_open: 'Open until 22:00',
    content_type_id: 12,
    no_checkin_members: 2,
    premium: false,
    is_premium: 0,
    is_women_only: 0,
    is_dca_approved_only: 0,
    allowed_plan_ids: [
      101, 114, 112, 111, 113, 91, 109, 106, 88, 102, 90, 92, 89, 105, 100,
    ],
    is_favorite: null,
    is_at_full_capacity: false,
    credits_required: 6,
    is_ddr: false,
    total_capacity_ar: '٢٠',
    credits_required_ar: '٦',
    spotLeft: 18,
    spotLeft_ar: '١٨',
    review_count_ar: '١٩',
    branch_cost: 'AED 30',
    branch_cost_ar: 'AED ٣٠',
  },
  {
    id: 263,
    location: 2,
    name: 'Amici Miei',
    total_capacity: 10,
    lat: 25.20655,
    lon: 55.344,
    review_count: 65,
    average_rating: 4.4,
    featured_image:
      'https://staging.letswork.io/media/general/image_from_ios-2.jpg',
    food_policy:
      'No outside food is permitted. Instead, enjoy 20% off your food and beverage order while working from this space.',
    checkin_instructions:
      "When you arrive at the cafe, please check-in on the Letswork App and inform the staff you're with Letswork to get your benefits.",
    address: 'Vida Creek Harbour Hotel',
    facilities: [
      {
        name: 'Free Parking',
        icon: 'https://staging.letswork.io/media/facilities/f_free_parking.png',
      },
      {
        name: 'Meeting Rooms',
        icon: 'https://staging.letswork.io/media/facilities/f_meeting_rooms.png',
      },
      {
        name: 'Toilets',
        icon: 'https://staging.letswork.io/media/facilities/f_toilets.png',
      },
      {
        name: 'WiFi',
        icon: 'https://staging.letswork.io/media/facilities/f_wifi.png',
      },
    ],
    wifi_password: 'N/A',
    wifi_name: 'Vida Hotels',
    speciality: 'Hotel - Quiet - Free Valet Parking',
    media: [
      {
        id: 628,
        title: 'img1',
        media_type: 'Image',
        media_url:
          'https://staging.letswork.io/media/general/image_from_ios-2.jpg',
        is_front: false,
      },
    ],
    thumbnail:
      'https://staging.letswork.io/media/med/400x400_resized_image_from_ios-2.jpg',
    timings: '00:01 - 23:00',
    is_open: 1,
    is_branch_open: 'Open until 23:00',
    content_type_id: 12,
    no_checkin_members: 2,
    premium: false,
    is_premium: 0,
    is_women_only: 0,
    is_dca_approved_only: 0,
    allowed_plan_ids: [
      101, 114, 112, 111, 113, 91, 109, 106, 88, 102, 90, 92, 89, 105, 100,
    ],
    is_favorite: null,
    is_at_full_capacity: false,
    credits_required: 7,
    is_ddr: false,
    total_capacity_ar: '١٠',
    credits_required_ar: '٧',
    spotLeft: 8,
    spotLeft_ar: '٨',
    review_count_ar: '٦٥',
    branch_cost: 'AED 35',
    branch_cost_ar: 'AED ٣٥',
  },
  {
    id: 15,
    location: 2,
    name: 'Arabian Ranches Golf Club',
    total_capacity: 10,
    lat: 25.051534,
    lon: 55.268708,
    review_count: 1270,
    average_rating: 4.9,
    featured_image: 'https://staging.letswork.io/media/general/ar10.jpg',
    food_policy:
      'No outside food permitted. Instead, enjoy 20% off your food and beverage order while working from this space.',
    checkin_instructions:
      'Letswork operates out of the ""The Restaurant"" at the Arabian Ranches Golf Club. Please check in on the app upon arrival and let the staff know you\'re with Letswork to enjoy your benefits. High tables in the venue have plug access & members can also ask the staff for where they can find more plug points.',
    address: 'Ranches Golf Club',
    facilities: [
      {
        name: 'Free Parking',
        icon: 'https://staging.letswork.io/media/facilities/f_free_parking.png',
      },
      {
        name: 'Toilets',
        icon: 'https://staging.letswork.io/media/facilities/f_toilets.png',
      },
      {
        name: 'WiFi',
        icon: 'https://staging.letswork.io/media/facilities/f_wifi.png',
      },
    ],
    wifi_password: 'Open WiFi',
    wifi_name: 'Open WiFi',
    speciality: 'Cafe - Lively - Free Parking',
    media: [
      {
        id: 73,
        title: null,
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/branch_images/ar2.jpg',
        is_front: false,
      },
      {
        id: 74,
        title: null,
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/branch_images/ar4.jpg',
        is_front: false,
      },
      {
        id: 75,
        title: null,
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/branch_images/ar6.jpg',
        is_front: false,
      },
      {
        id: 256,
        title: null,
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/general/ar8.jpg',
        is_front: false,
      },
      {
        id: 257,
        title: null,
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/general/ar10.jpg',
        is_front: false,
      },
    ],
    thumbnail: 'https://staging.letswork.io/media/med/400x400_resized_ar10.jpg',
    timings: '08:30 - 23:59',
    is_open: 1,
    is_branch_open: 'Open until 23:59',
    content_type_id: 12,
    no_checkin_members: 2,
    premium: false,
    is_premium: 0,
    is_women_only: 0,
    is_dca_approved_only: 0,
    allowed_plan_ids: [
      101, 114, 112, 111, 113, 91, 109, 106, 88, 102, 90, 92, 89, 105, 100,
    ],
    is_favorite: null,
    is_at_full_capacity: false,
    credits_required: 125,
    is_ddr: false,
    total_capacity_ar: '١٠',
    credits_required_ar: '١٢٥',
    spotLeft: 8,
    spotLeft_ar: '٨',
    review_count_ar: '١٢٧٠',
    branch_cost: 'AED 625',
    branch_cost_ar: 'AED ٦٢٥',
  },
  {
    id: 307,
    location: 2,
    name: 'Arrows and Sparrows Cafe',
    total_capacity: 8,
    lat: 25.096355508118958,
    lon: 55.16766578465411,
    review_count: 36,
    average_rating: 4.4,
    featured_image: 'https://staging.letswork.io/media/general/img_1324.jpg',
    food_policy:
      'No outside food permitted. Instead, enjoy 15% off your food and beverage order while working from this space.',
    checkin_instructions:
      'Once you arrive at the cafe, please check-in on the Letswork App and inform the staff you are with Letswork to enjoy your benefits.',
    address: '4 4a Street, Emaar Business Park',
    facilities: [
      {
        name: 'Paid Parking',
        icon: 'https://staging.letswork.io/media/facilities/f_paid_parking.png',
      },
      {
        name: 'Toilets',
        icon: 'https://staging.letswork.io/media/facilities/f_toilets.png',
      },
      {
        name: 'WiFi',
        icon: 'https://staging.letswork.io/media/facilities/f_wifi.png',
      },
    ],
    wifi_password: 'wearefriends',
    wifi_name: 'A&SGuest',
    speciality: 'Cafe - Lively - Paid Parking',
    media: [
      {
        id: 719,
        title: 'img1',
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/general/img_1324.jpg',
        is_front: false,
      },
      {
        id: 720,
        title: 'img2',
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/general/img_1327.jpg',
        is_front: false,
      },
      {
        id: 721,
        title: 'img3',
        media_type: 'Image',
        media_url: 'https://staging.letswork.io/media/general/img_1328.jpg',
        is_front: false,
      },
    ],
    thumbnail:
      'https://staging.letswork.io/media/med/400x400_resized_img_1324.jpg',
    timings: '07:00 - 22:00',
    is_open: 1,
    is_branch_open: 'Open until 22:00',
    content_type_id: 12,
    no_checkin_members: 0,
    premium: false,
    is_premium: 0,
    is_women_only: 0,
    is_dca_approved_only: 0,
    allowed_plan_ids: [
      101, 114, 112, 111, 113, 91, 109, 106, 88, 102, 90, 92, 89, 105, 100,
    ],
    is_favorite: null,
    is_at_full_capacity: false,
    credits_required: 7,
    is_ddr: false,
    total_capacity_ar: '٨',
    credits_required_ar: '٧',
    spotLeft: 8,
    spotLeft_ar: '٨',
    review_count_ar: '٣٦',
    branch_cost: 'AED 35',
    branch_cost_ar: 'AED ٣٥',
  },
];

export {VENUES};
